### PR TITLE
feat: add terse mode

### PR DESCRIPTION
**Pull request by spiral-ladder**
includes changes from https://github.com/FuelLabs/sway/pull/2870

### CODE REVIEW

**Comment by bingcicle** [comment]
This has to go in as well but `forc-pkg 0.24.5` still does not have the `terse_mode` changes, so we have to wait on a new forc release here.

**Comment by spiral-ladder** [comment]
This has to go in as well to unblock https://github.com/FuelLabs/sway/pull/2806 since `forc-pkg` has the `terse_mode` updates in the path version. I'm doing a [patch](https://github.com/FuelLabs/sway/pull/2806/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542R30-R38) in that PR to avoid fetching unnecessarily from crates.io. However we're in an awkward circular dependency thing for now since the `forc-pkg` used in path within the sway repo and the `forc-pkg` used here have diverged.

Marking this as blocked for now.

**Comment by mitchmindtree** [comment]
> However we're in an awkward circular dependency thing for now since the forc-pkg used in path within the sway repo and the forc-pkg used here have diverged.

Aghhhh I forgot `forc-client` was used within the Sway E2E `test`s... :facepalm:

This is going to continually cause problems as the `forc-client` used within Sway tests will necessarily always have to be at least a version behind the rest of `forc`, which will inevitably lead to incompatibilities when `forc-pkg` needs to make some breaking change that `forc-client` doesn't yet have.

The only options coming to mind off the top of my head are:

1. Refactor the Sway tests to use the SDK to deploy tests directly. But this would basically mean re-implementing `forc-client` just for the tests, and no longer testing the actual `forc-client` as a part of the E2E tests. :x: 
2. Move `deploy`/`run` tests downstream, but this would mean a whole extra step of indirection between changes to Sway and when problems show up downstream in tests. :x: 
3. Leave `forc-client` in the Sway repo.

As long as the Sway E2E tests use `forc` and its plugins, we're probably going to need to keep those plugins hosted under the main `Sway` repo even if they are conceptually distinct from the language.

As annoying as it is @bingcicle after all your work in `fuelup` to switch over to the `forc-client` repo there, I'm thinking we might be best to leave `forc-client` hosted under the Sway repo. That said, I'm open to other suggestions!

cc @adlerjohn

**Comment by spiral-ladder** [comment]
Hmm, this makes me wonder about the motivation behind https://github.com/FuelLabs/sway/issues/2412. Shouldn't `forc deploy` and `forc run` still be part of `forc` in that case, if they're so tightly coupled?

My assumption behind these changes was that we want to move as much `forc` functionality out of the Sway repo as we can to manage bloat within forc.

**Comment by mitchmindtree** [comment]
>  Hmm, this makes me wonder about the motivation behind https://github.com/FuelLabs/sway/issues/2412. Shouldn't forc deploy and forc run still be part of forc in that case, if they're so tightly coupled?

The intention is to take advantage of `forc`'s plugin modularity yes, but this is separate from the current problem at hand.

The problem at hand is that **the Sway E2E tests** depend on `forc-client` in order to deploy contracts and run scripts on a local `fuel-core` node.

Just because the Sway E2E tests require `forc-client` does not mean that other downstream users will. E.g. they might be content with some combination of stock `forc` and using the SDK directly.

Having `deploy` and `run` in a dedicated `forc-client` crate also speeds up development of `forc` a little as moving those commands into a dedicated plugin removes a few dependencies from `forc`.

> My assumption behind these changes was that we want to move as much forc functionality out of the Sway repo as we can to manage bloat within forc.

The goal was to move non-Sway-related crates out of the Sway repo if possible, however we're not going to have a good time attempting to remove crates that both 1. are a hard requirement for the Sway E2E tests and 2. depend on Sway (as `forc-client` does via `forc-pkg`).

**Comment by adlerjohn** [comment]
Avoiding circular dependencies takes precedence over cute separation of concerns IMO.

**Pull request closed without merging**
